version: '3.8'
services:
  user-service:
    build:
      context: ../user_service
      dockerfile: Dockerfile
  #    target: runtime
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      store-db:
        condition: service_healthy
      redis-service:
        condition: service_started
    ports:
      - "5001:5000"

  store-service:
    build:
      context: D:/Rahul/Projects/store-service/store_service/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      store-db:
        condition: service_healthy
      redis-service:
        condition: service_started
    ports:
      - "5002:5000"

  store-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - store_service_db:/var/lib/mysql
    # Port exposed to allow local database access and migration script generation
    ports:
      - "3306:3306"

  redis-service:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"

volumes:
  store_service_db: