name: user service build
on:
  push:
    branches:
      - main

jobs:
  sast:
    name: Security Analysis
    uses: ./.github/workflows/sast.yaml
    with:
      target-environment: production
    secrets: inherit
  
  ci:
    name: Build and Test
    needs: sast
    uses: ./.github/workflows/reusable-ci.yaml
    with:
      service-name: user-service
      docker-repo: daemons
      target-environment: production
    secrets: inherit

  zap:
    name: OWASP ZAP Scan
    needs: ci
    uses: ./.github/workflows/zap.yaml
    with:
      target-url: https://marry-fifty-rocky.ngrok-free.dev
    secrets: inherit